version: "~> 1.0"
language: node_js
os: linux
dist: focal
if: branch = "stable" OR tag IS present
jobs:
  include:
  - stage: Test the project
    name: Test the project on Linux with NodeJS 16
    os: linux
    dist: focal
    services:
    - xvfb
    node_js: '16'
    script: npm run build && npm run test
  - stage: Release to NPM
    name: Publish the package to the npmjs repository
    os: linux
    dist: focal
    node_js: '16'
    script: npm run build
    deploy:
      edge: true
      provider: npm
      email: npmjs@eraud.dev
      api_token:
        secure: dWI8Cudl7XAy5xvys3UU6ym+4CLQ22bIAjRcFOiflLVOGLLSVw43fA95cstZZ0ZHU2EMSWOWewpCw82uGyGN8oJDHclriEeL4LwwYFJuErTPVAeAr/2wqUmDfPAEF3qjT/74kPUm4nDul/7uMDvbhLJC/+Pvw2UMnh7ajVwtF3hgiF9aaUpuZr5FyCPjE20UM1VB3EaGsy+NiDEcqW7RDnjSD48YB3sxeH8n61Gj6HdRi2HsFcMMOK5qUw/byGn2WK++xT5BXoT4CbwdMGlf0FPAgEYIXtUUl6kk9e3kd8PjXKuoXLbh5AM45AjEIAEKJxlhjd9sY4U5VL7l+1Qvc2m0J5O6hVueOMN98qFTo2NTJBGq76lxvAhbXIcelLiHWAXG9R0d2E/Z3X2L5qgP+Qz62C5GWSK41cYoU6G0fkvD9nHejIYq7/SCc6HJHGeZVSdo5dBH3u3tjfwVg+V1N9s7o2rYtWvChOdc+u1W8OxCOYGNkvu8qHj1/Op+xx+iAz2WqhqR8e9688mxuvo8yXtItSRcYCahZoR8v+0PxeVE+dbKe2krr7WVNP5SIP2RVtosYRHbFDOS22IVz9ZNFrB8GtsQCMO6+OKiWAEw92tb2r/w+0zSwyzqDzBzXxbuwqNCokVwgfUcR6ChPFr7wggZsycLCqnShfFrf33jqNc=
      on:
        tags: true
        repo: lesjoursfr/audio-waveform
        branch: stable
      cleanup: false
notifications:
  slack:
    secure: QUbZZEj1xdxhg9zkNf2U7TUs8OOoEFRnxnaFIG3dNUguxmtl2EOTYE0+yuRMzgjl/qIFYFiuqJo8DDZqd/YSrHbkkXpf7EVu9QNp7gzrrwpKGAeloBrtu+rPUQZTp1JUiVQRqk06meMHRl5n4n5UILURT1gD9VU6lPNq9KlLXu6pI+ne+YSnn3ty3mNrCMCe/f2teUHOQyz8+1aDlWnfYua0GnoAB1JjnsJwtt7YDSRuMAFYEyJ2C5vg5c+O1CVjkEbG6mRJeDO4a/M0C6xbN3Hj5tbL/+Bvz3ARbwKDZdsOZ8Q6cw0nMycqbQsZbSqYRO4jL9G9RywrP0D9loITZLx+w/a6AWKf1/5n+UL1dcoLCcpVuHiZVo9zLD6CXY/bHNFFD/QbyjymGgxgA1j2IMHo4UO022NY9t2k3OVSYae4Bi5A7JfhbFO0Z8mBLBSJDFBiivGhUewGRTsUKUxMUdfOIMCqrqGrxmu9oAmiDcwC603S9l9B15Ozfwn4mgsVRzfarxCN2KUMirlPopLh+eQ0yPy+bMjhsBkZzoTnQJoijEOEWEeAUakEcN4VN7eb3trWFg14ToY+a/sI/WgiLBDKon8fQmsAv8/ApBfk0bA9h1n2K7L+5tEvK/vfjdDKqSsmoV+4jdBkNJmCOjJ80R8biqz4gihHTZ/pD+XboXY=
